name: gallery_picker
description: Gallery Picker is a flutter package that will allow you to pick media file(s), manage and navigate inside your gallery with modern tools and views.
version: 0.5.1
homepage: https://github.com/FlutterWay/gallery_picker
publish_to: none

environment:
  sdk: ">=3.5.2 <4.0.0"
  flutter: ">=3.24.3"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  photo_gallery:
    git: https://github.com/kumsumit/photo_gallery.git
  permission_handler:
    git: https://github.com/kumsumit/permission_handler.git
  transparent_image: ^2.0.1
  media_kit:
    git: https://github.com/kumsumit/media_kit.git
  media_kit_video:
    git: https://github.com/kumsumit/media_kit_video.git
  media_kit_libs_video:
    git: https://github.com/kumsumit/media_kit_libs_video.git
  device_info_plus:
    git: https://github.com/kumsumit/device_info_plus.git
  video_thumbnail_plugin:
    git: "https://github.com/sumitsharansatsangi/video_thumbnail_plugin.git"
  intl: ^0.20.0
  page_transition: ^2.1.0
  bottom_sheet_scaffold:
    git: https://github.com/sumitsharansatsangi/bottom_sheet_scaffold.git
  path: "^1.9.0"
  path_provider:
    git: "https://github.com/kumsumit/path_provider.git"
  get:
    git: https://github.com/jonataslaw/getx.git
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

dependency_overrides:
  plugin_platform_interface:
    git: https://github.com/kumsumit/plugin_platform_interface.git

flutter:
