name: gallery_picker
description: Gallery Picker is a flutter package that will allow you to pick media file(s), manage and navigate inside your gallery with modern tools and views.
version: 0.5.1
homepage: https://github.com/FlutterWay/gallery_picker
publish_to: none

environment:
  sdk: '>=3.5.2 <4.0.0'
  flutter: ">=3.24.3"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  photo_gallery:
    git: https://github.com/kumsumit/photo_gallery.git
  permission_handler:
    git: https://github.com/kumsumit/permission_handler.git
  transparent_image: ^2.0.1
  media_kit: '^1.1.11'
  media_kit_libs_video: '^1.0.5'
  media_kit_video: '^1.2.5'
  device_info_plus: 
    git: https://github.com/kumsumit/device_info_plus.git
  video_thumbnail:
    git: https://github.com/kumsumit/video_thumbnail.git
  intl: ^0.19.0
  page_transition: ^2.1.0
  bottom_sheet_scaffold: ^0.1.9
  path: '^1.9.0'
  path_provider: 
    git: 'https://github.com/kumsumit/path_provider.git'
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

dependency_overrides:
  plugin_platform_interface:
    git: https://github.com/kumsumit/plugin_platform_interface.git

flutter: