name: gallery_picker
description: Gallery Picker is a flutter package that will allow you to pick media file(s), manage and navigate inside your gallery with modern tools and views.
version: 0.5.1
homepage: https://github.com/FlutterWay/gallery_picker
publish_to: none

environment:
  sdk: '>=3.5.2 <4.0.0'
  flutter: ">=3.24.3"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  photo_gallery: ^2.2.1
  permission_handler:
    git: https://github.com/kumsumit/permission_handler.git
  transparent_image: ^2.0.1
  video_player: 
    git: https://github.com/kumsumit/video_player.git
  device_info_plus: 
    git: https://github.com/kumsumit/device_info_plus.git
  get: ^4.6.6
  video_thumbnail:
    git: https://github.com/kumsumit/video_thumbnail.git
  intl: ^0.19.0
  page_transition: ^2.1.0
  bottom_sheet_scaffold: ^0.1.9
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  
flutter: